version = 1

test_patterns = ["tests/"]

[[analyzers]]
name = "rust"

[analyzers.meta]
msrv = "stable"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "ruff"

[[code_formatters]]
name = "rustfmt"
